/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class ReturnRefund202309GetRejectReasonsResponseDataReasons {
    /**
    * The reject reason key. Pass this exact value to the corresponding seller reject API as the reject reason. Note: The available reject reasons may change depending on the current aftersales request context. To avoid using stale or inapplicable reason keys, call this API close to the reject action and use the latest returned name values instead of hardcoding them.
    */
    'name'?: string;
    /**
    * The corresponding text to the reason name, localized based on the locale input parameter.
    */
    'text'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202309GetRejectReasonsResponseDataReasons.attributeTypeMap;
    }
}

