/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliatePartner202508GetAffiliateCampaignCreatorProductSampleStatusResponseDataSampleStatus } from './GetAffiliateCampaignCreatorProductSampleStatusResponseDataSampleStatus';

export class AffiliatePartner202508GetAffiliateCampaignCreatorProductSampleStatusResponseData {
    'sampleStatus'?: AffiliatePartner202508GetAffiliateCampaignCreatorProductSampleStatusResponseDataSampleStatus;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sampleStatus",
            "baseName": "sample_status",
            "type": "AffiliatePartner202508GetAffiliateCampaignCreatorProductSampleStatusResponseDataSampleStatus"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202508GetAffiliateCampaignCreatorProductSampleStatusResponseData.attributeTypeMap;
    }
}

