/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliatePartner202603SearchTapAffiliateOrdersRequestBody {
    /**
    * Filter orders by a TAP campaign using its identifier.
    */
    'campaignId'?: string;
    /**
    * Filter orders to show only those that are created on or after the specified date and time. Unix timestamp. Please note that we only support 3 months\' data at maximum for each single request. Note: `create_time_ge` and `create_time_lt` together constitute the creation time filter condition. `create_time_ge` and `create_time_lt` must be provided together. If both are not specified, data from the last three months will be queried by default.
    */
    'createTimeGe'?: number;
    /**
    * Filter orders to show only those that are created before the specified date and time. Unix timestamp. Refer to notes in `create_time_ge` for more usage information.
    */
    'createTimeLt'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "campaignId",
            "baseName": "campaign_id",
            "type": "string"
        },
        {
            "name": "createTimeGe",
            "baseName": "create_time_ge",
            "type": "number"
        },
        {
            "name": "createTimeLt",
            "baseName": "create_time_lt",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202603SearchTapAffiliateOrdersRequestBody.attributeTypeMap;
    }
}

