/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrders } from './SearchTapAffiliateOrdersResponseDataSkuOrders';

export class AffiliatePartner202603SearchTapAffiliateOrdersResponseData {
    /**
    * Cursor used for searching for more information
    */
    'nextPageToken'?: string;
    /**
    * Order list
    */
    'skuOrders'?: Array<AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrders>;
    /**
    * The total number of sku orders
    */
    'totalCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "skuOrders",
            "baseName": "sku_orders",
            "type": "Array<AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrders>"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202603SearchTapAffiliateOrdersResponseData.attributeTypeMap;
    }
}

