/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualCommissionBase } from './SearchTapAffiliateOrdersResponseDataSkuOrdersActualCommissionBase';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualCreatorShopAdsCommission } from './SearchTapAffiliateOrdersResponseDataSkuOrdersActualCreatorShopAdsCommission';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualCreatorStandardCommission } from './SearchTapAffiliateOrdersResponseDataSkuOrdersActualCreatorStandardCommission';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualCreatorTapBonusCommission } from './SearchTapAffiliateOrdersResponseDataSkuOrdersActualCreatorTapBonusCommission';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerIsr } from './SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerIsr';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerIva } from './SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerIva';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerShopAdsCommission } from './SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerShopAdsCommission';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerStandardCommission } from './SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerStandardCommission';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerTapBonusCommission } from './SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerTapBonusCommission';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCommissionBase } from './SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCommissionBase';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorShopAdsCommission } from './SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorShopAdsCommission';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorStandardCommission } from './SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorStandardCommission';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorTapBonusCommission } from './SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorTapBonusCommission';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerIsr } from './SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerIsr';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerIva } from './SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerIva';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerShopAdsCommission } from './SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerShopAdsCommission';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerStandardCommission } from './SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerStandardCommission';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerTapBonusCommission } from './SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerTapBonusCommission';
import { AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersPrice } from './SearchTapAffiliateOrdersResponseDataSkuOrdersPrice';

export class AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrders {
    'actualCommissionBase'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualCommissionBase;
    'actualCreatorShopAdsCommission'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualCreatorShopAdsCommission;
    'actualCreatorStandardCommission'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualCreatorStandardCommission;
    'actualCreatorTapBonusCommission'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualCreatorTapBonusCommission;
    'actualPartnerIsr'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerIsr;
    'actualPartnerIva'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerIva;
    'actualPartnerShopAdsCommission'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerShopAdsCommission;
    'actualPartnerStandardCommission'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerStandardCommission;
    'actualPartnerTapBonusCommission'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerTapBonusCommission;
    /**
    * New seller campaign
    */
    'campaignId'?: string;
    /**
    * Unique identifier for content
    */
    'contentId'?: string;
    /**
    * The content format of the creator content through which the order was created. Possible values: - SHOP - VIDEO - LIVE - PRE_LIVE - PROMOTION_PAGE - LINKSHARE
    */
    'contentType'?: string;
    /**
    * Time and date of order created, UTC+0 timing
    */
    'createTime'?: number;
    /**
    * Between TAP & creator percentage shop ads commission
    */
    'creatorShopAdsCommissionRate'?: number;
    /**
    * Between TAP & creator percentage commission
    */
    'creatorStandardCommissionRate'?: number;
    /**
    * The commission reward rate affiliate partners allocate to creators
    */
    'creatorTapBonusCommissionRate'?: number;
    /**
    * Creator username
    */
    'creatorUsername'?: string;
    /**
    * Time and date order delivered, UTC+0 timing
    */
    'deliveryTime'?: number;
    'estimatedCommissionBase'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCommissionBase;
    'estimatedCreatorShopAdsCommission'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorShopAdsCommission;
    'estimatedCreatorStandardCommission'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorStandardCommission;
    'estimatedCreatorTapBonusCommission'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorTapBonusCommission;
    'estimatedPartnerIsr'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerIsr;
    'estimatedPartnerIva'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerIva;
    'estimatedPartnerShopAdsCommission'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerShopAdsCommission;
    'estimatedPartnerStandardCommission'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerStandardCommission;
    'estimatedPartnerTapBonusCommission'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerTapBonusCommission;
    /**
    * Return “Yes” when this sku is fully returned/refunded. No commission given when full return/refund
    */
    'fullyReturn'?: string;
    /**
    * Transaction main order ID
    */
    'id'?: string;
    /**
    * The time when the record was last updated.
    */
    'lastUpdateTime'?: number;
    /**
    * Between TAP & seller percentage shop ads commission
    */
    'partnerShopAdsCommissionRate'?: number;
    /**
    * Between seller & TAP percentage commission
    */
    'partnerStandardCommissionRate'?: number;
    /**
    * The additional commission rate TikTok Shop offers to affiliate partners for driving product sales in specific campaigns
    */
    'partnerTapBonusCommissionRate'?: number;
    'price'?: AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersPrice;
    /**
    * Unique identifier for Product
    */
    'productId'?: string;
    /**
    * Product name / description
    */
    'productName'?: string;
    /**
    * Total sku quantity per order
    */
    'quantity'?: number;
    /**
    * Settlement Status of the order. Possible values: 1. \"CUSTOMER UNPAID\",  customer hasn\'t paid for the orders. 2. \"PENDING\", customers can still return or get a refund for this order. The earnings shown are estimates and waiting for settlement. 3. \"SETTLED\", your earnings have already settled to your account 4. \"INELIGIBLE\", The order has been returned/refunded/canceled by the buyer, and no commission will be settled. 5. \"FROZEN\", Possible fraud has been detected regarding the order. The commission will be unfrozen after the fraud is resolved.
    */
    'settleStatus'?: string;
    /**
    * Time and date of order commission settled. UTC+0 Timing
    */
    'settlementTime'?: number;
    /**
    * sku ID
    */
    'skuId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "actualCommissionBase",
            "baseName": "actual_commission_base",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualCommissionBase"
        },
        {
            "name": "actualCreatorShopAdsCommission",
            "baseName": "actual_creator_shop_ads_commission",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualCreatorShopAdsCommission"
        },
        {
            "name": "actualCreatorStandardCommission",
            "baseName": "actual_creator_standard_commission",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualCreatorStandardCommission"
        },
        {
            "name": "actualCreatorTapBonusCommission",
            "baseName": "actual_creator_tap_bonus_commission",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualCreatorTapBonusCommission"
        },
        {
            "name": "actualPartnerIsr",
            "baseName": "actual_partner_isr",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerIsr"
        },
        {
            "name": "actualPartnerIva",
            "baseName": "actual_partner_iva",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerIva"
        },
        {
            "name": "actualPartnerShopAdsCommission",
            "baseName": "actual_partner_shop_ads_commission",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerShopAdsCommission"
        },
        {
            "name": "actualPartnerStandardCommission",
            "baseName": "actual_partner_standard_commission",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerStandardCommission"
        },
        {
            "name": "actualPartnerTapBonusCommission",
            "baseName": "actual_partner_tap_bonus_commission",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerTapBonusCommission"
        },
        {
            "name": "campaignId",
            "baseName": "campaign_id",
            "type": "string"
        },
        {
            "name": "contentId",
            "baseName": "content_id",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "string"
        },
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "number"
        },
        {
            "name": "creatorShopAdsCommissionRate",
            "baseName": "creator_shop_ads_commission_rate",
            "type": "number"
        },
        {
            "name": "creatorStandardCommissionRate",
            "baseName": "creator_standard_commission_rate",
            "type": "number"
        },
        {
            "name": "creatorTapBonusCommissionRate",
            "baseName": "creator_tap_bonus_commission_rate",
            "type": "number"
        },
        {
            "name": "creatorUsername",
            "baseName": "creator_username",
            "type": "string"
        },
        {
            "name": "deliveryTime",
            "baseName": "delivery_time",
            "type": "number"
        },
        {
            "name": "estimatedCommissionBase",
            "baseName": "estimated_commission_base",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCommissionBase"
        },
        {
            "name": "estimatedCreatorShopAdsCommission",
            "baseName": "estimated_creator_shop_ads_commission",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorShopAdsCommission"
        },
        {
            "name": "estimatedCreatorStandardCommission",
            "baseName": "estimated_creator_standard_commission",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorStandardCommission"
        },
        {
            "name": "estimatedCreatorTapBonusCommission",
            "baseName": "estimated_creator_tap_bonus_commission",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorTapBonusCommission"
        },
        {
            "name": "estimatedPartnerIsr",
            "baseName": "estimated_partner_isr",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerIsr"
        },
        {
            "name": "estimatedPartnerIva",
            "baseName": "estimated_partner_iva",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerIva"
        },
        {
            "name": "estimatedPartnerShopAdsCommission",
            "baseName": "estimated_partner_shop_ads_commission",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerShopAdsCommission"
        },
        {
            "name": "estimatedPartnerStandardCommission",
            "baseName": "estimated_partner_standard_commission",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerStandardCommission"
        },
        {
            "name": "estimatedPartnerTapBonusCommission",
            "baseName": "estimated_partner_tap_bonus_commission",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerTapBonusCommission"
        },
        {
            "name": "fullyReturn",
            "baseName": "fully_return",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "lastUpdateTime",
            "baseName": "last_update_time",
            "type": "number"
        },
        {
            "name": "partnerShopAdsCommissionRate",
            "baseName": "partner_shop_ads_commission_rate",
            "type": "number"
        },
        {
            "name": "partnerStandardCommissionRate",
            "baseName": "partner_standard_commission_rate",
            "type": "number"
        },
        {
            "name": "partnerTapBonusCommissionRate",
            "baseName": "partner_tap_bonus_commission_rate",
            "type": "number"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrdersPrice"
        },
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        },
        {
            "name": "productName",
            "baseName": "product_name",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "settleStatus",
            "baseName": "settle_status",
            "type": "string"
        },
        {
            "name": "settlementTime",
            "baseName": "settlement_time",
            "type": "number"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202603SearchTapAffiliateOrdersResponseDataSkuOrders.attributeTypeMap;
    }
}

